version: "3.1"
services:
  db:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED:true
      - INFLUXDB_HOST:localhost
    ports:
      - 8083:8083
      - 8086:8086
  api:
    image: echurchill/web-api:0.1.0
    ports:
      - 1337:1337
    links:
      - db
  dashboard:
    image: grafana/grafana
    ports:
      - 3000:3000
