version: "3.1"
services:
  mongo:
    image: mongo
    ports:
      - 27017:27017
  influx:
    image: influxdb
    environment:
      - INFLUXDB_ADMIN_ENABLED:true
    ports:
      - 8083:8083
      - 8086:8086
  api:
    image: echurchill/iot-web-api:0.1.3
    ports:
      - 1337:1337
    links:
      - mongo
      - influx
  dashboard:
    image: grafana/grafana
    ports:
      - 3000:3000
